# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7980c87290086e9b52cd66c7b7b588c03ab5cd7cb2562574fc467d579d8bf57826751630de8b7b01865b38f6da0fd396160e1fd07ee47b854c72496d78d619a9

test:
  secret_key_base: 356537ffb5f3edf0af9c3c35327acdd237f3a9f882dd34a2250f191a1e79236921a9139de65ebc068eb072553455586d88e644c0f3ae2e84a3f285e0dc369f2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
